services:

  mysql:
    image: mysql:8.4
    container_name: heroes_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroes

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend

    container_name: heroes_backend

    ports:
      - "3000:3000"

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: heroes

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend

    container_name: heroes_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data: